first-active-range = [1, 5]
active-window-range = [2, 12]
min-stable-interval = 3

max-active-cells = 6
ever-active-bounds = [4, 4]

pattern-center = [5, 3]
pattern = '''
x = 9, y = 9, rule = LifeHistory
.A$2.A$3A2$4.5B$4.5B$4.5B$4.5B$4.5B!
'''
